const actionTypes = {
  PRODUCT_LIST_REQUEST: 'PRODUCT_LIST_REQUEST',
  PRODUCT_LIST_SUCCESS: 'PRODUCT_LIST_SUCCESS',
  PRODUCT_LIST_FAIL: 'PRODUCT_LIST_FAIL',

  PRODUCT_DETAILS_REQUEST: 'PRODUCT_DETAILS_REQUEST',
  PRODUCT_DETAILS_SUCCESS: 'PRODUCT_DETAILS_SUCCESS',
  PRODUCT_DETAILS_FAIL: 'PRODUCT_DETAILS_FAIL',

  PRODUCT_DELETE_REQUEST: 'PRODUCT_DELETE_REQUEST',
  PRODUCT_DELETE_SUCCESS: 'PRODUCT_DELETE_SUCCESS',
  PRODUCT_DELETE_FAIL: 'PRODUCT_DELETE_FAIL',

  PRODUCT_CREATE_REQUEST: 'PRODUCT_CREATE_REQUEST',
  PRODUCT_CREATE_SUCCESS: 'PRODUCT_CREATE_SUCCESS',
  PRODUCT_CREATE_FAIL: 'PRODUCT_CREATE_FAIL',
  PRODUCT_CREATE_RESET: 'PRODUCT_CREATE_RESET',

  PRODUCT_UPDATE_REQUEST: 'PRODUCT_UPDATE_REQUEST',
  PRODUCT_UPDATE_SUCCESS: 'PRODUCT_UPDATE_SUCCESS',
  PRODUCT_UPDATE_FAIL: 'PRODUCT_UPDATE_FAIL',
  PRODUCT_UPDATE_RESET: 'PRODUCT_UPDATE_RESET',

  CART_ADD_ITEM: 'CART_ADD_ITEM',
  CART_REMOVE_ITEM: 'CART_REMOVE_ITEM',
  CART_SAVE_SHIPPING_ADDRESS: 'CART_SAVE_SHIPPING_ADDRESS',
  CART_SAVE_PAYMENT_METHOD: 'CART_SAVE_PAYMENT_METHOD',

  ORDER_CREATE_REQUEST: 'ORDER_CREATE_REQUEST',
  ORDER_CREATE_SUCCESS: 'ORDER_CREATE_SUCCESS',
  ORDER_CREATE_FAIL: 'ORDER_CREATE_FAIL',

  ORDER_DETAILS_REQUEST: 'ORDER_DETAILS_REQUEST',
  ORDER_DETAILS_SUCCESS: 'ORDER_DETAILS_SUCCESS',
  ORDER_DETAILS_FAIL: 'ORDER_DETAILS_FAIL',

  ORDER_PAY_REQUEST: 'ORDER_PAY_REQUEST',
  ORDER_PAY_SUCCESS: 'ORDER_PAY_SUCCESS',
  ORDER_PAY_FAIL: 'ORDER_PAY_FAIL',
  ORDER_PAY_RESET: 'ORDER_PAY_RESET',

  USER_LOGIN_REQUEST: 'USER_LOGIN_REQUEST',
  USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',

  ORDER_USER_LIST_REQUEST: 'ORDER_USER_LIST_REQUEST',
  ORDER_USER_LIST_SUCCESS: 'ORDER_USER_LIST_SUCCESS',
  ORDER_USER_LIST_FAIL: 'ORDER_USER_LIST_FAIL',
  ORDER_USER_LIST_RESET: 'ORDER_USER_LIST_RESET',

  USER_LOGOUT: 'USER_LOGOUT',

  USER_REGISTER_REQUEST: 'USER_REGISTER_REQUEST',
  USER_REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
  USER_REGISTER_FAIL: 'USER_REGISTER_FAIL',

  USER_ADMIN_LIST_REQUEST: 'USER_ADMIN_LIST_REQUEST',
  USER_ADMIN_LIST_SUCCESS: 'USER_ADMIN_LIST_SUCCESS',
  USER_ADMIN_LIST_FAIL: 'USER_ADMIN_LIST_FAIL',
  USER_ADMIN_LIST_RESET: 'USER_ADMIN_LIST_RESET',

  USER_ADMIN_UPDATE_REQUEST: 'USER_ADMIN_UPDATE_REQUEST',
  USER_ADMIN_UPDATE_SUCCESS: 'USER_ADMIN_UPDATE_SUCCESS',
  USER_ADMIN_UPDATE_FAIL: 'USER_ADMIN_UPDATE_FAIL',
  USER_ADMIN_UPDATE_RESET: 'USER_ADMIN_UPDATE_RESET',

  USER_ADMIN_DELETE_REQUEST: 'USER_ADMIN_DELETE_REQUEST',
  USER_ADMIN_DELETE_SUCCESS: 'USER_ADMIN_DELETE_SUCCESS',
  USER_ADMIN_DELETE_FAIL: 'USER_ADMIN_DELETE_FAIL',

  USER_DETAILS_REQUEST: 'USER_DETAILS_REQUEST',
  USER_DETAILS_SUCCESS: 'USER_DETAILS_SUCCESS',
  USER_DETAILS_FAIL: 'USER_DETAILS_FAIL',
  USER_DETAILS_RESET: 'USER_DETAILS_RESET',

  USER_UPDATE_PROFILE_REQUEST: 'USER_UPDATE_PROFILE_REQUEST',
  USER_UPDATE_PROFILE_SUCCESS: 'USER_UPDATE_PROFILE_SUCCESS',
  USER_UPDATE_PROFILE_FAIL: 'USER_UPDATE_PROFILE_FAIL',
  USER_UPDATE_PROFILE_RESET: 'USER_UPDATE_PROFILE_RESET'
};

export default actionTypes;
